name: "ll_project"
type: "python:3.12"

relationships:
  database: "db.postgresql"

# Konfiguracja aplikacji, gdy nie jest udostępniona w internecie.

web:
  upstream:
    socket_family: unix
  commands:
    start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
  locations:
    "/":
      passthru: true
    "/static":
      root: "static"
      expires: 1h
      allow: true
# Wyrażona w megabajtach ilość miejsca na dysku zarezerwowana dla aplikacji.
disk: 512

# Określenie lokalnych punktów montowania dla dzienników zdarzeń.
mounts:
  "logs":
    source: local
    source_path: logs

# Zaczepy wykonywane w różnych punktach cyklu życiowego aplikacji.
hooks:
  build: |
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirements_remote.txt

    mkdir logs
    python manage.py collectstatic
    rm -rf logs
  deploy: |
    python manage.py migrate