# Każda trasa opisuje sposób przetwarzania przez serwer Platform.sh przychodzącego adresu URL.
"https://{default}/":
  type: upstream
  upstream: "ll_project:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"